"use client";

import { useState } from "react";
import { Download, Shield, AlertCircle, ServerOff } from "lucide-react";
import Section, { PageContainer, SectionHeader } from "@/components/layout/Section";
import Card, { CardHeader, CardTitle } from "@/components/ui/Card";
import Button from "@/components/ui/Button";
import Badge from "@/components/ui/Badge";
import FileUpload from "@/components/demos/FileUpload";
import FraudResults from "@/components/demos/FraudResults";
import {
  predictFraudBatch,
  downloadFraudResults,
  isFraudApiConfigured,
  getFraudApiUrl,
} from "@/lib/api";
import type { FraudAnalysisResponse } from "@/lib/types";

export default function FraudDetectionDemoPage() {
  const [results, setResults] = useState<FraudAnalysisResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const apiConfigured = isFraudApiConfigured();

  const handleFileSelect = async (file: File) => {
    setLoading(true);
    setError(null);
    setResults(null);
    try {
      const data = await predictFraudBatch(file);
      setResults(data);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Failed to reach the fraud detection API."
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <Section className="pt-8">
      <PageContainer>
        <SectionHeader
          title="Fraud Detection Demo"
subtitle="Upload transaction data and analyze fraud risk using my XGBoost-based fraud detection system deployed with FastAPI and Docker."        />

        <div className="flex flex-wrap gap-3 mb-8">
          <Badge variant="primary">
            <Shield className="h-3 w-3 mr-1" />
            XGBoost Model
          </Badge>
<Badge variant="accent">FastAPI + Docker</Badge>
<Badge variant="default">Batch Inference</Badge>        </div>
<div className="flex flex-wrap gap-3 mb-8 text-sm text-muted">
  <span>ROC-AUC: 0.997</span>
  <span>•</span>
  <span>F1: 0.861</span>
  <span>•</span>
  <span>50k+ Batch Predictions Supported</span>
</div>
        {!apiConfigured && (
          <Card className="mb-8 border-warning/30">
            <div className="flex items-start gap-3 text-warning">
              <ServerOff className="h-5 w-5 shrink-0 mt-0.5" />
              <div>
                <p className="font-medium text-foreground">Inference Service Unavailable</p>
                <p className="text-sm text-muted mt-1">
                  Set{" "}
                  <code className="text-xs bg-surface-elevated px-1.5 py-0.5 rounded">
                    NEXT_PUBLIC_FRAUD_API_URL
                  </code>{" "}
                  to your deployed fraud detection FastAPI service to enable
                  this demo.
                </p>
              </div>
            </div>
          </Card>
        )}

        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Upload Transaction Data</CardTitle>
          </CardHeader>
          <p className="text-sm text-muted mb-6">
            CSV is sent to{" "}
            <code className="text-xs bg-surface-elevated px-1.5 py-0.5 rounded">
              {apiConfigured
                ? `${getFraudApiUrl()}/predict_batch`
                : "{FRAUD_API_URL}/predict_batch"}
            </code>
            . Predictions are generated by the deployed FastAPI backend using an XGBoost model trained on over 1.2 million transactions.
          </p>
          <FileUpload
            onFileSelect={handleFileSelect}
            loading={loading}
            disabled={!apiConfigured}
          />
        </Card>

        {error && (
          <Card className="mb-8 border-danger/30">
            <div className="flex items-start gap-3 text-danger">
              <AlertCircle className="h-5 w-5 shrink-0 mt-0.5" />
              <div>
                <p className="font-medium">Request Failed</p>
                <p className="text-sm mt-1 opacity-80">{error}</p>
              </div>
            </div>
          </Card>
        )}

        {results && (
          <>
            <div className="flex justify-end mb-6">
              <Button
                variant="secondary"
                onClick={() => downloadFraudResults(results)}
              >
                <Download className="h-4 w-4" />
                Download Predictions CSV
              </Button>
            </div>
            <FraudResults data={results} />
          </>
        )}
      </PageContainer>
    </Section>
  );
}
